%include "iftCommon.i"
%include "iftMImage.i"
%include "iftAdjacency.i"
%include "iftGraphics.i"
%include "iftFiltering.i"
%include "iftInterpolation.i"
%include "iftClustering.i"
%include "iftSVM.i"
%include "iftKmeans.i"
%include "iftTensor.i"

